# Generated by Django 4.2.27 on 2025-12-31 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'saved_artists',
            },
        ),
        migrations.CreateModel(
            name='SavedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'saved_tracks',
            },
        ),
        migrations.CreateModel(
            name='SpotifyCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(max_length=50)),
                ('expires_in', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('scope', models.TextField()),
            ],
            options={
                'db_table': 'spotify_credentials',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user', max_length=250)),
                ('age', models.IntegerField(help_text='User age, must be adult (+18)')),
                ('music_preferences', models.JSONField(blank=True, default=list, help_text='List of preferred genres')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('age__gt', 18), ('age__lt', 120)), name='age_range_ck'),
        ),
        migrations.AddField(
            model_name='spotifycredentials',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_credentials', to='app.user'),
        ),
        migrations.AddField(
            model_name='savedtrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tracks', to='app.user'),
        ),
        migrations.AddField(
            model_name='savedartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_artists', to='app.user'),
        ),
        migrations.AddIndex(
            model_name='savedtrack',
            index=models.Index(fields=['user', 'spotify_id'], name='ix_track_user_sid'),
        ),
        migrations.AddConstraint(
            model_name='savedtrack',
            constraint=models.UniqueConstraint(fields=('user', 'spotify_id'), name='uq_track_user_sid'),
        ),
        migrations.AddIndex(
            model_name='savedartist',
            index=models.Index(fields=['user', 'spotify_id'], name='ix_artist_user_sid'),
        ),
        migrations.AddConstraint(
            model_name='savedartist',
            constraint=models.UniqueConstraint(fields=('user', 'spotify_id'), name='uq_artist_user_sid'),
        ),
    ]
